### ISSUE TITLE
Some possible stylistic changes

### ISSUE THREAD

**Issue by MugsyCarter** [markgreenwood/portfolio#27]
You website looks and functions great!  I couldn't see anything to improve so here are a few stylistic additions you might consider making if you have some time on your hands.

-add some flair to your clicks.  I love the highlight on hover and the pointer icon that you already have for your clicks.  You could also add a click sound or make the button look like it's been depressed.

-Make the mobile version look significantly different from the computer version. I like the look of your header with your photo, it may be neat to have you header large and centered as the home screen and then change the screen to reveal the projects or the "about" sections.

-maybe add a little space to the margins between the bottoms and tops or your articles to match the top and bottom margins of the section.

-make the footer a little smaller to match the margins of the text contained within.

If you don't make any of these changes your portfolio will still look great.  Nice job!

**Comment by markgreenwood** [comment]
Most fixed and merged in PR #29
