### ISSUE TITLE
CSS that should be in modules.css

### ISSUE THREAD

**Issue by nthugon** [markgreenwood/portfolio#7]
In base.css you have an entry for #about
[code here](https://github.com/markgreenwood/portfolio/blob/master/styles/base.css#L16-L18)
In layout.css you have header and article img
[code here](https://github.com/markgreenwood/portfolio/blob/master/styles/base.css#L16-L18)
[code here](https://github.com/markgreenwood/portfolio/blob/master/styles/layout.css#L21-L24)
I think that these items would be more appropriately placed in modules.css as they are specific components

**Comment by markgreenwood** [comment]
Fixed - merged in PR #10
